create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, daily_goal integer default 10, created_at timestamptz default now());
-- Stable question IDs are strings such as L01-Q001, not generated integers.
-- Production installs should apply the ordered migrations in supabase/migrations/.
create table if not exists public.answer_attempts (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete cascade not null, lesson_id integer not null, exercise_id text not null, answer text not null, verdict text not null, error_tags text[] default '{}', created_at timestamptz default now());
create table if not exists public.review_items (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete cascade not null, lesson_id integer not null, exercise_id text not null, due_at timestamptz not null default now(), interval_days integer not null default 0, ease numeric default 2.5, reps integer default 0, lapses integer default 0, unique(user_id, lesson_id, exercise_id));
alter table public.profiles enable row level security;
alter table public.answer_attempts enable row level security;
alter table public.review_items enable row level security;
create policy "own profile" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "own attempts" on public.answer_attempts for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "own 已完成reviews" on public.review_items for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
