'use client'
import {useEffect,useRef,useState} from 'react'
import {courses} from '@/lib/courses'
import {getSupabaseBrowser} from '@/lib/supabase'
import {questionForId,questionsForLesson, type Question} from '@/lib/question-bank'

const courseLessons=courses.map((c)=>({...c,progress:0,locked:false}))
const completedFromLessonProgress=(progress:Record<number,number>,explicit:unknown)=>{const values=Array.isArray(explicit)?explicit.filter((n):n is number=>Number.isInteger(n)&&n>=0&&n<courses.length):[];const derived=Object.entries(progress).filter(([,count])=>typeof count==='number'&&count>=10).map(([index])=>Number(index));return Array.from(new Set([...values,...derived])).sort((a,b)=>a-b)}
export default function Home(){
 const [tab,setTab]=useState('home'); const [active,setActive]=useState(0); const [input,setInput]=useState(''); const [graded,setGraded]=useState(false); const [done,setDone]=useState(0); const [userEmail,setUserEmail]=useState(''); const [userId,setUserId]=useState(''); const [cloudLoaded,setCloudLoaded]=useState(false); const [syncState,setSyncState]=useState<'local'|'syncing'|'synced'|'failed'>('local'); const [syncRetry,setSyncRetry]=useState(0); const currentUserId=useRef(''); const cloudApplied=useRef(false)
 const [reviewDone,setReviewDone]=useState(0); const [minutes,setMinutes]=useState(0); const [claimed,setClaimed]=useState({new:false,review:false,time:false,bonus:false}); const [practiceMode,setPracticeMode]=useState<'new'|'review'|'mistakes'>('new'); const [completedLessons,setCompletedLessons]=useState<number[]>([]); const [lessonDone,setLessonDone]=useState<Record<number,number>>({}); const [mistakes,setMistakes]=useState<Question[]>([]); const [mistakeIndex,setMistakeIndex]=useState(0); const [aiVerdict,setAiVerdict]=useState<'correct'|'mostly_correct'|'needs_fix'|'incorrect'|null>(null); const [gradeExplanation,setGradeExplanation]=useState(''); const [gradeSource,setGradeSource]=useState<'ai'|'rule'|null>(null); const [analysis,setAnalysis]=useState<{analysis?:string;words?:{word:string;kana:string;meaning:string;memory:string}[];pitfalls?:string[];source?:string}|null>(null); const [analysisLoading,setAnalysisLoading]=useState(false); const [dailyLoaded,setDailyLoaded]=useState(false); const [completedLoaded,setCompletedLoaded]=useState(false); const [lessonLoaded,setLessonLoaded]=useState(false); const [mistakesLoaded,setMistakesLoaded]=useState(false)
 const [dueQuestionIds,setDueQuestionIds]=useState<string[]>([])
 useEffect(()=>{const s=getSupabaseBrowser();if(!s){setCloudLoaded(true);return}
  let mounted=true
  const applyUser=(user:NonNullable<Awaited<ReturnType<typeof s.auth.getUser>>['data']['user']>)=>{if(!mounted)return;cloudApplied.current=true;setSyncState('synced');const accountChanged=Boolean(currentUserId.current&&currentUserId.current!==user.id);if(accountChanged){setDone(0);setReviewDone(0);setMinutes(0);setClaimed({new:false,review:false,time:false,bonus:false});setLessonDone({});setCompletedLessons([]);setMistakes([])}currentUserId.current=user.id;setUserId(user.id);setUserEmail(user.email||'');const progress=user.user_metadata?.learning_progress;if(progress){const savedDone=typeof progress.done==='number'?Math.max(0,Math.min(10,progress.done)):0;if(typeof progress.done==='number')setDone(savedDone);if(typeof progress.reviewDone==='number')setReviewDone(progress.reviewDone);if(typeof progress.minutes==='number')setMinutes(progress.minutes);const cloudLessonDone=progress.lessonDone&&typeof progress.lessonDone==='object'?progress.lessonDone as Record<number,number>:{};const normalizedLessonDone=Object.keys(cloudLessonDone).length?cloudLessonDone:(savedDone>0?{0:savedDone}:{});if(Object.keys(normalizedLessonDone).length)setLessonDone(normalizedLessonDone);if(Object.keys(normalizedLessonDone).length||Array.isArray(progress.completedLessons))setCompletedLessons(completedFromLessonProgress(normalizedLessonDone,progress.completedLessons));if(Array.isArray(progress.mistakes))setMistakes(progress.mistakes as Question[]);if(progress.claimed&&typeof progress.claimed==='object')setClaimed(progress.claimed as {new:boolean;review:boolean;time:boolean;bonus:boolean})}setCloudLoaded(true)}
  s.auth.getUser().then(({data})=>{if(!mounted)return;if(data.user)applyUser(data.user);else{cloudApplied.current=false;currentUserId.current='';setUserId('');setUserEmail('');setSyncState('local');setCloudLoaded(true)}})
  const {data}=s.auth.onAuthStateChange((event,session)=>{const user=session?.user;if(!user){cloudApplied.current=false;currentUserId.current='';setUserId('');setUserEmail('');setSyncState('local');setCloudLoaded(true);return}if(event==='SIGNED_IN'&&user.id!==currentUserId.current){setCloudLoaded(false);applyUser(user)}})
  return ()=>{mounted=false;data.subscription.unsubscribe()}
 },[])
 useEffect(()=>{if(!cloudLoaded||!userId)return;const s=getSupabaseBrowser();if(!s)return;const syncedCompleted=completedFromLessonProgress(lessonDone,completedLessons);const timer=window.setTimeout(()=>{void (async()=>{setSyncState('syncing');const {error}=await s.auth.updateUser({data:{learning_progress:{version:1,done,reviewDone,minutes,lessonDone,completedLessons:syncedCompleted,mistakes,claimed,updatedAt:new Date().toISOString()}}});if(error){console.error('Failed to sync learning progress',error);setSyncState('failed');return}setSyncState('synced')})()},500);return()=>window.clearTimeout(timer)},[cloudLoaded,userId,done,reviewDone,minutes,lessonDone,completedLessons,mistakes,claimed,syncRetry])
 useEffect(()=>{if(!userId)return;let cancelled=false;void (async()=>{try{const response=await fetch('/api/study-state');if(!response.ok)return;const state=await response.json();if(cancelled)return;const daily=state.daily;if(daily){setDone(daily.new_done||0);setReviewDone(daily.review_done||0);setMinutes(daily.minutes||0);setClaimed({new:Boolean(daily.claimed_new),review:Boolean(daily.claimed_review),time:Boolean(daily.claimed_time),bonus:Boolean(daily.claimed_bonus)})}const persistedLessons=Object.fromEntries((state.lessons||[]).map((lesson:{lesson_id:number;answered_count:number})=>[lesson.lesson_id-1,lesson.answered_count]));if(Object.keys(persistedLessons).length){setLessonDone(persistedLessons);setCompletedLessons(completedFromLessonProgress(persistedLessons,(state.lessons||[]).filter((lesson:{completed_at:string|null})=>lesson.completed_at).map((lesson:{lesson_id:number})=>lesson.lesson_id-1)))}setDueQuestionIds(Array.isArray(state.dueQuestionIds)?state.dueQuestionIds:[])}catch{console.warn('Unable to load durable study state; using local fallback')}})();return()=>{cancelled=true}},[userId])
 useEffect(()=>{if(cloudApplied.current){setDailyLoaded(true);return}const key=`syntax-coach-daily-${new Date().toLocaleDateString('sv-SE')}`;const saved=localStorage.getItem(key);if(saved){try{const data=JSON.parse(saved);setDone(data.done||0);setReviewDone(data.reviewDone||0);setMinutes(data.minutes||0);setClaimed(data.claimed||{new:false,review:false,time:false,bonus:false})}catch{localStorage.removeItem(key)}}setDailyLoaded(true)},[])
 useEffect(()=>{if(cloudApplied.current){setCompletedLoaded(true);return}const saved=localStorage.getItem('syntax-coach-completed-lessons');if(saved){try{const parsed=JSON.parse(saved);if(Array.isArray(parsed))setCompletedLessons(parsed.filter((n):n is number=>Number.isInteger(n)&&n>=0&&n<courses.length))}catch{localStorage.removeItem('syntax-coach-completed-lessons')}}setCompletedLoaded(true)},[])
 useEffect(()=>{if(cloudApplied.current){setLessonLoaded(true);return}const saved=localStorage.getItem('syntax-coach-lesson-progress');if(saved){try{const parsed=JSON.parse(saved);if(parsed&&typeof parsed==='object'){const normalized=Object.fromEntries(Object.entries(parsed).filter(([index,count])=>Number.isInteger(Number(index))&&Number(index)>=0&&Number(index)<courses.length&&typeof count==='number').map(([index,count])=>[Number(index),Math.max(0,Math.min(10,count as number))]));setLessonDone(normalized);setCompletedLessons(value=>completedFromLessonProgress(normalized,value))}}catch{localStorage.removeItem('syntax-coach-lesson-progress')}}setLessonLoaded(true)},[])
 useEffect(()=>{if(cloudApplied.current){setMistakesLoaded(true);return}const saved=localStorage.getItem('syntax-coach-mistakes');if(saved){try{const parsed=JSON.parse(saved);if(Array.isArray(parsed))setMistakes(parsed)}catch{localStorage.removeItem('syntax-coach-mistakes')}}setMistakesLoaded(true)},[])
 useEffect(()=>{if(mistakesLoaded)localStorage.setItem('syntax-coach-mistakes',JSON.stringify(mistakes))},[mistakes,mistakesLoaded])
 useEffect(()=>{if(lessonLoaded)localStorage.setItem('syntax-coach-lesson-progress',JSON.stringify(lessonDone))},[lessonDone,lessonLoaded])
 useEffect(()=>{if(completedLoaded)localStorage.setItem('syntax-coach-completed-lessons',JSON.stringify(completedLessons))},[completedLessons,completedLoaded])
 useEffect(()=>{if(tab==='home'&&lessonDone[active]>=10)setCompletedLessons(value=>value.includes(active)?value:[...value,active])},[tab,active,lessonDone])
 useEffect(()=>{if(dailyLoaded){const key=`syntax-coach-daily-${new Date().toLocaleDateString('sv-SE')}`;localStorage.setItem(key,JSON.stringify({done,reviewDone,minutes,claimed}))}},[done,reviewDone,minutes,claimed,dailyLoaded])
 useEffect(()=>{const timer=window.setInterval(()=>{if(!document.hidden){setMinutes(value=>Math.min(20,value+1));if(userId)void fetch('/api/update-daily',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({minuteDelta:1})})}},60000);return()=>window.clearInterval(timer)},[userId])
 useEffect(()=>{if(!graded)setAiVerdict(null)},[graded])
 const activeLessonDone=lessonDone[active]??0
 const displayedLessons=courseLessons.map((lesson,index)=>({...lesson,progress:Math.min(100,Math.round(((lessonDone[index]??0)/10)*100)),locked:index>0&&!completedLessons.includes(index-1)}))
 const lessons=displayedLessons
 const selectedLesson=displayedLessons[Math.min(active,displayedLessons.length-1)]
 const firstIncompleteLesson=displayedLessons.findIndex(lesson=>!lesson.locked&&lesson.progress<100)
 const nextLessonIndex=firstIncompleteLesson>=0?firstIncompleteLesson:displayedLessons.length-1
 useEffect(()=>{if(tab==='practice'&&practiceMode==='new'&&activeLessonDone>=10&&nextLessonIndex!==active)setActive(nextLessonIndex)},[tab,practiceMode,activeLessonDone,nextLessonIndex,active])
 const progress=practiceMode==='new'?activeLessonDone:practiceMode==='review'?reviewDone:mistakeIndex; const sessionLimit=practiceMode==='new'?10:practiceMode==='review'?5:Math.max(1,mistakes.length)
 const currentGrammar=selectedLesson.grammar[progress%selectedLesson.grammar.length]
 const lessonQuestions=questionsForLesson(selectedLesson.id)
 const priorGrammar=active>0?displayedLessons[active-1]?.grammar[progress%displayedLessons[active-1].grammar.length]:undefined
 const isReviewQuestion=active>0&&progress%10>=7
 const dueReviewQuestions=dueQuestionIds.map(questionForId).filter((question):question is Question=>Boolean(question))
 const reviewQuestions=dueReviewQuestions.length?dueReviewQuestions:(active>0?questionsForLesson(selectedLesson.id-1):[])
 const sourceQuestions=practiceMode==='mistakes'?mistakes:practiceMode==='review'?reviewQuestions:(isReviewQuestion&&reviewQuestions.length?reviewQuestions:lessonQuestions)
 const bankQuestion=sourceQuestions.length?sourceQuestions[progress%sourceQuestions.length]:undefined
 const ex=bankQuestion??(isReviewQuestion&&priorGrammar?{id:`L${String(active).padStart(2,'0')}-R${String(progress+1).padStart(3,'0')}`,lessonId:active,type:'翻译',prompt:`复习第 ${active} 课：请根据「${priorGrammar.meaning}」表达一个句子。`,answer:priorGrammar.example,hint:`旧课句型：${priorGrammar.pattern}`}:{id:`L${String(active+1).padStart(2,'0')}-Q${String(progress+1).padStart(3,'0')}`,lessonId:active+1,type:'翻译',prompt:`请根据「${currentGrammar.meaning}」表达一个句子。`,answer:currentGrammar.example,hint:`句型：${currentGrammar.pattern}`})
 const cleaned=(s:string)=>s.replace(/[\s。！？!?，,、．.]/g,'')
 const localAnswerMatches=cleaned(input)===cleaned(ex.answer)
 const answerMatches=aiVerdict?aiVerdict==='correct'||aiVerdict==='mostly_correct':localAnswerMatches
 const missingPunctuation=answerMatches&&/[。．.]$/.test(ex.answer)&&!/[。．.]$/.test(input.trim())
 const grade=()=>{setAiVerdict(null);setAnalysis(null);setGradeExplanation(localAnswerMatches?'句型结构正确，继续保持主动输出。':'先对照句型骨架检查助词、否定形式和句尾。');setGradeSource('rule');if(!localAnswerMatches){setMistakes(value=>value.some(item=>item.id===ex.id)?value:[...value,ex])}else if(practiceMode==='mistakes'){setMistakes(value=>value.filter(item=>item.id!==ex.id))}if(userId)void (async()=>{try{const response=await fetch('/api/record-answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:ex.id,lessonId:ex.lessonId,answer:input,correct:localAnswerMatches,errorTags:localAnswerMatches?[]:['句型顺序'],mode:practiceMode})});if(!response.ok)return;const {record}=await response.json();if(practiceMode==='new'&&typeof record?.lessonAnsweredCount==='number'){setLessonDone(value=>({...value,[active]:record.lessonAnsweredCount}));if(record.lessonAnsweredCount>=10)setCompletedLessons(value=>value.includes(active)?value:[...value,active])}if(!localAnswerMatches)setDueQuestionIds(value=>value.includes(ex.id)?value:[ex.id,...value])}catch{console.warn('Unable to persist answer; using local fallback')}})();setGraded(true)}
 const analyzeAnswer=async()=>{setAnalysisLoading(true);try{const response=await fetch('/api/analyze-answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:ex.prompt,answer:input,standardAnswer:ex.answer,hint:ex.hint})});setAnalysis(await response.json())}catch{setAnalysis({analysis:'AI 分析暂时不可用，请对照标准答案拆分词语和句型记忆。',source:'fallback'})}finally{setAnalysisLoading(false)}}
 const displayCorrect=aiVerdict?aiVerdict==='correct'||aiVerdict==='mostly_correct':answerMatches
 const startPractice=(mode:'new'|'review',lessonIndex=active)=>{setPracticeMode(mode);setActive(lessonIndex);setInput('');setAiVerdict(null);setGraded(false);setTab('practice')}
 const startMistakePractice=()=>{if(mistakes.length){setPracticeMode('mistakes');setMistakeIndex(0);setInput('');setAiVerdict(null);setGraded(false);setTab('practice')}}
 const nextQuestion=()=>{const complete=progress>=sessionLimit-1;if(practiceMode==='new'){setDone(value=>Math.min(10,value+1));setLessonDone(value=>({...value,[active]:Math.min(10,(value[active]??0)+1)}))}else if(practiceMode==='review')setReviewDone(value=>Math.min(5,value+1));else setMistakeIndex(value=>value+1);setInput('');setGraded(false);if(complete)setTab('home')}
 const taskStatus={new:done>=10,review:reviewDone>=5,time:minutes>=20}; const allTasks=taskStatus.new&&taskStatus.review&&taskStatus.time; const claim=(key:'new'|'review'|'time'|'bonus')=>{if(key==='new'&&!taskStatus.new)return;if(key==='review'&&!taskStatus.review)return;if(key==='time'&&!taskStatus.time)return;if(key==='bonus'&&!allTasks)return;setClaimed(c=>({...c,[key]:true}));if(userId)void fetch('/api/update-daily',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({claim:key})})}
 const todayProgress=Math.round((done/10)*100)
 const pendingReview=Math.max(0,5-reviewDone)
 const currentLesson=displayedLessons[nextLessonIndex]??displayedLessons[0]
 const overallProgress=Math.round(displayedLessons.reduce((sum,lesson)=>sum+lesson.progress,0)/displayedLessons.length)
 const learnerName=userEmail?userEmail.split('@')[0]:'学习者'
 const totalAnswered=Object.values(lessonDone).reduce((sum,count)=>sum+count,0)
 return <main className="shell">
   <header><div className="brand"><span className="brand-mark">文</span><div><strong>句型教练</strong><small>标准日本语 · 上册</small></div></div><div className={'streak '+(done>=10?'finished':'')}>{done>=10?'✓ 今日完成':`今日 ${done} / 10`}</div><button className="avatar" onClick={()=>setTab('me')}>{learnerName.slice(0,1).toUpperCase()}</button></header>
  {tab==='home'&&<><section className="hero"><div><p className="eyebrow">早上好，{learnerName}</p><h1>每天练习一点，<br/><em>把句型练成反射。</em></h1><p className="muted">今天完成 10 道主动输出练习，约需 20 分钟。</p><button className="primary" onClick={()=>startPractice('new',nextLessonIndex)}>开始今日训练 <span>→</span></button></div><div className="orb" style={{background:`conic-gradient(var(--green) 0 ${todayProgress}%,#dfe9e3 ${todayProgress}%`}}><div className="orb-inner">今日<br/><b>{todayProgress}%</b></div></div></section>
   <section className="stats"><div><b>{pendingReview}</b><span>今日待复习</span></div><div><b>第 {currentLesson.id} 课</b><span>继续学习</span></div><div><b>{overallProgress}%</b><span>整体掌握</span></div></section>
   <section className="section-head"><div><p className="eyebrow">今日目标</p><h2>完成目标，领取积分</h2></div><strong className="points">{(claimed.new?15:0)+(claimed.review?15:0)+(claimed.time?15:0)+(claimed.bonus?15:0)} 分</strong></section>
   <div className="daily-tasks"><div className={'task '+(taskStatus.new?'complete':'')}><span className="task-check">{taskStatus.new?'✓':'01'}</span><div><b>完成新的 10 道题</b><small>{Math.min(done,10)} / 10 · 主动输出</small></div>{taskStatus.new?<button className="claim" onClick={()=>claim('new')} disabled={claimed.new}>{claimed.new?'已领取':'领取 15 分'}</button>:<button className="task-action" onClick={()=>startPractice('new',nextLessonIndex)}>去完成</button>}</div><div className={'task '+(taskStatus.review?'complete':'')}><span className="task-check">{taskStatus.review?'✓':'02'}</span><div><b>完成 5 道复习题</b><small>{reviewDone} / 5 · 间隔复习</small></div>{taskStatus.review?<button className="claim" onClick={()=>claim('review')} disabled={claimed.review}>{claimed.review?'已领取':'领取 15 分'}</button>:<button className="task-action" onClick={()=>startPractice('review',nextLessonIndex)}>去复习</button>}</div><div className={'task '+(taskStatus.time?'complete':'')}><span className="task-check">{taskStatus.time?'✓':'03'}</span><div><b>累计学习 20 分钟</b><small>{minutes} / 20 分钟 · 专注学习</small></div>{taskStatus.time?<button className="claim" onClick={()=>claim('time')} disabled={claimed.time}>{claimed.time?'已领取':'领取 15 分'}</button>:<span className="task-status">页面学习中自动累计</span>}</div>{allTasks&&<div className="bonus-task"><span>🎉</span><div><b>三项任务全部完成</b><small>额外奖励 15 分</small></div><button className="claim bonus" onClick={()=>claim('bonus')} disabled={claimed.bonus}>{claimed.bonus?'已领取':'领取 15 分'}</button></div>}</div>
   <section className="section-head"><div><p className="eyebrow">继续学习</p><h2>{currentLesson.progress>0?'接着上次学习':'从第一课开始'}</h2></div><button className="link" onClick={()=>setTab('lessons')}>查看全部 →</button></section>
<div className="lesson-card" onClick={()=>{setActive(nextLessonIndex);setTab('lesson')}}><div className="lesson-no">{String(currentLesson.id).padStart(2,'0')}</div><div className="lesson-info"><div className="tag">第 {currentLesson.id} 课</div><h3>{currentLesson.title}</h3><p>{currentLesson.grammar.map(g=>g.pattern).join(' · ')}</p><div className="progress"><i style={{width:`${currentLesson.progress}%`}}/></div><small>{currentLesson.progress?`已掌握 ${currentLesson.progress}%`:'尚未开始'}</small></div><span className="arrow">→</span></div>
   <section className="section-head"><div><p className="eyebrow">复习安排</p><h2>间隔复习</h2></div></section><div className="review-row">{[['今天',pendingReview,'待复习'],['明天','—','暂无安排'],['+3 天','—','暂无安排'],['+7 天','—','暂无安排']].map(([d,count,label],i)=><div className={i===0?'review active':'review'} key={String(d)}><span>{d}</span><b>{count}</b><small>{label}</small></div>)}</div>
  </>}
  {tab==='lessons'&&<><div className="page-title"><p className="eyebrow">课程地图</p><h1>标准日本语·上册</h1><p className="muted">24 课 · 从句型骨架开始，逐步建立语感</p></div><div className="lesson-grid">{lessons.map(l=><button key={l.id} className={'lesson-tile '+(l.locked?'locked':'')} onClick={()=>!l.locked&&(setActive(l.id-1),setTab('lesson'))}><span>{String(l.id).padStart(2,'0')}</span><div><b>第 {l.id} 课</b><small>{l.title}</small>{!l.locked&&<div className="mini-progress"><i style={{width:`${l.progress}%`}}/></div>}</div><em>{l.locked?'🔒':l.progress+'%'}</em></button>)}</div></>}
  {tab==='lesson'&&<><button className="back" onClick={()=>setTab('home')}>← 返回</button><div className="page-title"><div className="tag">第 {selectedLesson.id} 课 · 核心句型</div><h1>{selectedLesson.title}</h1><p className="muted">{selectedLesson.goal}</p></div><div className="grammar-list">{selectedLesson.grammar.map((g,i)=><div className="grammar" key={i}><span>0{i+1}</span><div><b>{g.pattern}</b><p>{g.meaning}</p><small>接续：{g.connection}</small><small>说明：{g.explanation}</small><small>例句：{g.example}</small>{g.responses?.map(response=><small className="grammar-extra" key={response}>应答：{response}</small>)}{g.pitfalls?.map(pitfall=><small className="grammar-extra" key={pitfall}>易错：{pitfall}</small>)}</div><button onClick={()=>speechSynthesis?.speak(new SpeechSynthesisUtterance(g.example))}>🔊</button></div>)}</div><button className="primary wide" onClick={()=>setTab('practice')}>开始练习 <span>→</span></button></>}
  {tab==='practice'&&<><div className="practice-top"><button className="back" onClick={()=>setTab('home')}>× 退出</button><span>{practiceMode==='mistakes'?'错题练习':`第 ${selectedLesson.id} 课 · 练习`}</span><b>{Math.min(progress+1,sessionLimit)} / {sessionLimit}</b></div><div className="quiz"><div className="quiz-meta"><span className="tag">{ex.type}</span><span>句型骨架</span></div><h2>把下面的中文说成日语</h2><div className="prompt">{ex.prompt}</div><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="在这里输入你的答案…" disabled={graded}/>{graded&&<div className={'feedback '+(answerMatches?'ok':'warn')}><b>{answerMatches?'✓ 很好，句型正确':'△ 句型或词语还需要调整'}</b><p>参考答案：{ex.answer}</p>{gradeExplanation&&<small>{gradeSource==='ai'?'AI 批改：':'规则批改：'}{gradeExplanation}</small>}{missingPunctuation&&<small>答案判定正确；下次书写时不要忘记写标点符号。</small>}{!answerMatches&&<><small>提示：{ex.hint}<br/>书写时不要忘记写标点符号，标点不影响判分。</small></>}{!analysis&&<button className="analysis-button" onClick={analyzeAnswer} disabled={analysisLoading}>{analysisLoading?'分析中…':'AI 分析记忆方法'}</button>}{analysis&&<div className="analysis"><p>{analysis.analysis}</p>{analysis.words?.map(word=><div key={word.word}><b>{word.word}（{word.kana}）</b><span>{word.meaning} · {word.memory}</span></div>)}{analysis.pitfalls?.map(pitfall=><small key={pitfall}>易错点：{pitfall}</small>)}</div>}</div>}<button className="primary wide" onClick={()=>graded?nextQuestion():grade()}>{graded?(progress>=sessionLimit-1?'完成训练':'下一题'):'提交答案'} <span>→</span></button></div></>}
  {tab==='mistakes'&&<><div className="page-title"><p className="eyebrow">复习重点</p><h1>错题本</h1><p className="muted">把容易忘的地方，再练一次。</p></div>{mistakes.length>0&&<button className="primary wide" onClick={startMistakePractice}>开始错题练习（{mistakes.length} 题）</button>}{mistakes.map(item=><div className="mistake-card" key={item.id}><div className="mistake-icon">文</div><div><b>{item.prompt}</b><p>第 {item.lessonId} 课 · {item.type}</p><small>参考答案：{item.answer}</small></div><span>→</span></div>)}{mistakes.length===0&&<div className="empty-note">目前没有错题<br/>完成练习后，错题会自动收录。</div>}</>}
  {tab==='me'&&<><div className="page-title"><p className="eyebrow">个人中心</p><h1>我的</h1><p className="muted">学习记录会在登录后同步到云端。</p></div><div className="profile-card"><div className="profile-avatar">{userEmail?userEmail.slice(0,1).toUpperCase():'N'}</div><div><h2>{userEmail||'N 学习者'}</h2><p>{userEmail?'已登录':'尚未登录'}</p></div><button className="outline" onClick={()=>location.href='/login'}>{userEmail?'切换账号':'登录 / 注册'}</button></div>{userEmail&&<div className={'sync-note '+syncState}>{syncState==='syncing'?'正在同步学习记录…':syncState==='failed'?'同步失败，请检查网络后重试。':syncState==='synced'?'学习记录已同步到云端。':'仅保存在当前设备。'}{syncState==='failed'&&<button onClick={()=>setSyncRetry(value=>value+1)}>重试</button>}</div>}<div className="profile-stats"><div><b>第 {currentLesson.id} 课</b><span>当前课程</span></div><div><b>{overallProgress}%</b><span>学习进度</span></div><div><b>{(claimed.new?15:0)+(claimed.review?15:0)+(claimed.time?15:0)+(claimed.bonus?15:0)}</b><span>今日积分</span></div><div><b>{done} / 10</b><span>今日训练</span></div></div><div className="info-list"><div><span>同步状态</span><b>{userEmail?(syncState==='failed'?'需要重试':syncState==='syncing'?'同步中':syncState==='synced'?'已同步':'仅本机'):'登录后同步'}</b></div><div><span>已完成课程</span><b>{completedLessons.length} / 24</b></div><div><span>累计练习</span><b>{totalAnswered} 题</b></div></div></>}
  <nav><button className={tab==='home'?'selected':''} onClick={()=>setTab('home')}>⌂<small>首页</small></button><button className={tab==='lessons'||tab==='lesson'?'selected':''} onClick={()=>setTab('lessons')}>▤<small>课程</small></button><button className={tab==='mistakes'?'selected':''} onClick={()=>setTab('mistakes')}>☆<small>错题本</small></button><button className={tab==='me'?'selected':''} onClick={()=>setTab('me')}>◎<small>我的</small></button></nav>
 </main>
}
