'use client'
import {useEffect,useRef,useState} from 'react'
import {courses} from '@/lib/courses'
import {getSupabaseBrowser} from '@/lib/supabase'
import {questionsForLesson, type Question} from '@/lib/question-bank'
import {createMixedReviewSet} from '@/lib/review-set'

const courseLessons=courses.map((c)=>({...c,progress:0,locked:false}))
const completedFromLessonProgress=(progress:Record<number,number>,explicit:unknown)=>{const values=Array.isArray(explicit)?explicit.filter((n):n is number=>Number.isInteger(n)&&n>=0&&n<courses.length):[];const derived=Object.entries(progress).filter(([index,count])=>{const total=questionsForLesson(Number(index)+1).length||20;return typeof count==='number'&&count>=total}).map(([index])=>Number(index));return Array.from(new Set([...values,...derived])).sort((a,b)=>a-b)}
const explainAnswerDifference=(expected:string,actual:string)=>{
 const clean=(value:string)=>value.replace(/[。！？!?，,、．.\s]/g,'')
 const expectedClean=clean(expected);const actualClean=clean(actual)
 if(expectedClean===actualClean)return '句型和词语正确，但书写时请补上句末标点。'
 if(expected.includes('ですか')&&actual.includes('でか'))return '句尾疑问形式错误：你写成了「でか」，应为完整的「ですか」（缺少「す」）。'
 if(expected.includes('ではありません')&&actual.includes('でわありません'))return '否定形式的假名错误：「でわ」应写作「では」。'
 const limit=Math.min(expectedClean.length,actualClean.length);let index=0
 while(index<limit&&expectedClean[index]===actualClean[index])index++
 if(index<limit)return `第 ${index+1} 个字有误：你写的是「${actualClean[index]}」，应为「${expectedClean[index]}」。`
 if(actualClean.length<expectedClean.length)return `答案少了内容：第 ${actualClean.length+1} 个字应为「${expectedClean[actualClean.length]}」，请检查是否漏写。`
 if(actualClean.length>expectedClean.length)return `答案多了内容：请检查第 ${expectedClean.length+1} 个字「${actualClean[expectedClean.length]}」附近。`
 return '请逐字对照参考答案，检查助词、活用和句尾形式。'
}
export default function Home(){
 const [tab,setTab]=useState('home'); const [active,setActive]=useState(0); const [input,setInput]=useState(''); const [graded,setGraded]=useState(false); const [userEmail,setUserEmail]=useState(''); const [userId,setUserId]=useState(''); const [cloudLoaded,setCloudLoaded]=useState(false); const [syncState,setSyncState]=useState<'local'|'syncing'|'synced'|'failed'>('local'); const [syncRetry,setSyncRetry]=useState(0); const currentUserId=useRef(''); const cloudApplied=useRef(false)
 const [practiceMode,setPracticeMode]=useState<'lesson'|'mistakes'|'mixed'>('lesson'); const [completedLessons,setCompletedLessons]=useState<number[]>([]); const [lessonDone,setLessonDone]=useState<Record<number,number>>({}); const [lessonCorrect,setLessonCorrect]=useState<Record<number,number>>({}); const [mistakes,setMistakes]=useState<Question[]>([]); const [mixedQuestions,setMixedQuestions]=useState<Question[]>([]); const [aiVerdict,setAiVerdict]=useState<'correct'|'mostly_correct'|'needs_fix'|'incorrect'|null>(null); const [gradeExplanation,setGradeExplanation]=useState(''); const [gradeSource,setGradeSource]=useState<'ai'|'rule'|null>(null); const [analysis,setAnalysis]=useState<{analysis?:string;words?:{word:string;kana:string;meaning:string;memory:string}[];pitfalls?:string[];source?:string}|null>(null); const [analysisLoading,setAnalysisLoading]=useState(false); const [completedLoaded,setCompletedLoaded]=useState(false); const [lessonLoaded,setLessonLoaded]=useState(false); const [mistakesLoaded,setMistakesLoaded]=useState(false)
 const submittedQuestion=useRef<Question|null>(null)
 const [fullLessonMode,setFullLessonMode]=useState(false)
 const [selectedChoice,setSelectedChoice]=useState('')
 const [fullLessonProgress,setFullLessonProgress]=useState(0)
 const [sessionProgress,setSessionProgress]=useState(0)
 useEffect(()=>{const s=getSupabaseBrowser();if(!s){setCloudLoaded(true);return}
  let mounted=true
  const applyUser=(user:NonNullable<Awaited<ReturnType<typeof s.auth.getUser>>['data']['user']>)=>{if(!mounted)return;cloudApplied.current=true;setSyncState('synced');const accountChanged=Boolean(currentUserId.current&&currentUserId.current!==user.id);if(accountChanged){setLessonDone({});setLessonCorrect({});setCompletedLessons([]);setMistakes([])}currentUserId.current=user.id;setUserId(user.id);setUserEmail(user.email||'');const progress=user.user_metadata?.learning_progress;if(progress){const cloudLessonDone=progress.lessonDone&&typeof progress.lessonDone==='object'?progress.lessonDone as Record<number,number>:{};if(Object.keys(cloudLessonDone).length)setLessonDone(cloudLessonDone);if(Object.keys(cloudLessonDone).length||Array.isArray(progress.completedLessons))setCompletedLessons(completedFromLessonProgress(cloudLessonDone,progress.completedLessons));if(Array.isArray(progress.mistakes))setMistakes(progress.mistakes as Question[])}setCloudLoaded(true)}
  s.auth.getUser().then(({data})=>{if(!mounted)return;if(data.user)applyUser(data.user);else{cloudApplied.current=false;currentUserId.current='';setUserId('');setUserEmail('');setSyncState('local');setCloudLoaded(true)}})
  const {data}=s.auth.onAuthStateChange((event,session)=>{const user=session?.user;if(!user){cloudApplied.current=false;currentUserId.current='';setUserId('');setUserEmail('');setSyncState('local');setCloudLoaded(true);return}if(event==='SIGNED_IN'&&user.id!==currentUserId.current){setCloudLoaded(false);applyUser(user)}})
  return ()=>{mounted=false;data.subscription.unsubscribe()}
 },[])
 useEffect(()=>{if(!cloudLoaded||!userId)return;const s=getSupabaseBrowser();if(!s)return;const syncedCompleted=completedFromLessonProgress(lessonDone,completedLessons);const timer=window.setTimeout(()=>{void (async()=>{setSyncState('syncing');const {error}=await s.auth.updateUser({data:{learning_progress:{version:2,lessonDone,lessonCorrect,completedLessons:syncedCompleted,mistakes,updatedAt:new Date().toISOString()}}});if(error){console.error('Failed to sync learning progress',error);setSyncState('failed');return}setSyncState('synced')})()},500);return()=>window.clearTimeout(timer)},[cloudLoaded,userId,lessonDone,lessonCorrect,completedLessons,mistakes,syncRetry])
 useEffect(()=>{if(!userId)return;let cancelled=false;void (async()=>{try{const response=await fetch('/api/study-state');if(!response.ok)return;const state=await response.json();if(cancelled)return;const persistedLessons=Object.fromEntries((state.lessons||[]).map((lesson:{lesson_id:number;answered_count:number})=>[lesson.lesson_id-1,lesson.answered_count]));if(Object.keys(persistedLessons).length){setLessonDone(persistedLessons);setCompletedLessons(completedFromLessonProgress(persistedLessons,(state.lessons||[]).filter((lesson:{completed_at:string|null})=>lesson.completed_at).map((lesson:{lesson_id:number})=>lesson.lesson_id-1)))}}catch{console.warn('Unable to load durable study state; using local fallback')}})();return()=>{cancelled=true}},[userId])
 useEffect(()=>{if(!userId)return;let cancelled=false;void fetch('/api/study-state').then(response=>response.ok?response.json():null).then(state=>{if(cancelled||!state)return;const persistedCorrect=Object.fromEntries((state.lessons||[]).filter((lesson:{correct_count?:number})=>typeof lesson.correct_count==='number').map((lesson:{lesson_id:number;correct_count:number})=>[lesson.lesson_id-1,lesson.correct_count]));if(Object.keys(persistedCorrect).length)setLessonCorrect(persistedCorrect)}).catch(()=>console.warn('Unable to load lesson accuracy')).finally(()=>{cancelled=true});return()=>{cancelled=true}},[userId])
 useEffect(()=>{if(cloudApplied.current){setCompletedLoaded(true);return}const saved=localStorage.getItem('syntax-coach-completed-lessons');if(saved){try{const parsed=JSON.parse(saved);if(Array.isArray(parsed))setCompletedLessons(parsed.filter((n):n is number=>Number.isInteger(n)&&n>=0&&n<courses.length))}catch{localStorage.removeItem('syntax-coach-completed-lessons')}}setCompletedLoaded(true)},[])
 useEffect(()=>{if(cloudApplied.current){setLessonLoaded(true);return}const saved=localStorage.getItem('syntax-coach-lesson-progress');if(saved){try{const parsed=JSON.parse(saved);if(parsed&&typeof parsed==='object'){const normalized=Object.fromEntries(Object.entries(parsed).filter(([index,count])=>Number.isInteger(Number(index))&&Number(index)>=0&&Number(index)<courses.length&&typeof count==='number').map(([index,count])=>[Number(index),Math.max(0,Math.min(100,count as number))]));setLessonDone(normalized);setCompletedLessons(value=>completedFromLessonProgress(normalized,value))}}catch{localStorage.removeItem('syntax-coach-lesson-progress')}}setLessonLoaded(true)},[])
 useEffect(()=>{if(cloudApplied.current){setMistakesLoaded(true);return}const saved=localStorage.getItem('syntax-coach-mistakes');if(saved){try{const parsed=JSON.parse(saved);if(Array.isArray(parsed))setMistakes(parsed)}catch{localStorage.removeItem('syntax-coach-mistakes')}}setMistakesLoaded(true)},[])
 useEffect(()=>{if(mistakesLoaded)localStorage.setItem('syntax-coach-mistakes',JSON.stringify(mistakes))},[mistakes,mistakesLoaded])
 useEffect(()=>{if(lessonLoaded)localStorage.setItem('syntax-coach-lesson-progress',JSON.stringify(lessonDone))},[lessonDone,lessonLoaded])
 useEffect(()=>{if(completedLoaded)localStorage.setItem('syntax-coach-completed-lessons',JSON.stringify(completedLessons))},[completedLessons,completedLoaded])
 useEffect(()=>{const total=questionsForLesson(active+1).length||20;const answered=lessonDone[active]??0;const correct=lessonCorrect[active]??0;if(answered>=total&&correct/Math.max(1,answered)>=0.9)setCompletedLessons(value=>value.includes(active)?value:[...value,active])},[active,lessonDone,lessonCorrect])
 useEffect(()=>{if(!graded)setAiVerdict(null)},[graded])
 const activeLessonDone=lessonDone[active]??0
 const displayedLessons=courseLessons.map((lesson,index)=>{const total=questionsForLesson(lesson.id).length||20;return {...lesson,progress:Math.min(100,Math.round(((lessonDone[index]??0)/total)*100)),locked:index>0&&!completedLessons.includes(index-1)}})
 const lessons=displayedLessons
 const selectedLesson=displayedLessons[Math.min(active,displayedLessons.length-1)]
 const firstIncompleteLesson=displayedLessons.findIndex(lesson=>!lesson.locked&&lesson.progress<100)
 const nextLessonIndex=firstIncompleteLesson>=0?firstIncompleteLesson:displayedLessons.length-1
 const progress=fullLessonMode?fullLessonProgress:sessionProgress; const sessionLimit=practiceMode==='mistakes'?mistakes.length:practiceMode==='mixed'?mixedQuestions.length:(fullLessonMode?(questionsForLesson(selectedLesson.id).length||20):20)
 const lessonQuestions=questionsForLesson(selectedLesson.id)
 const sourceQuestions=practiceMode==='mistakes'?mistakes:practiceMode==='mixed'?mixedQuestions:lessonQuestions
 const bankQuestion=sourceQuestions.length?sourceQuestions[progress%sourceQuestions.length]:undefined
 const ex=bankQuestion??{id:`L${String(active+1).padStart(2,'0')}-Q${String(progress+1).padStart(3,'0')}`,lessonId:active+1,type:'翻译' as const,prompt:'本课题目正在准备中。',answer:'',hint:'请返回课程页后重试。'}
 const presentedQuestion=graded&&submittedQuestion.current?submittedQuestion.current:ex
 const cleaned=(s:string)=>s.replace(/[\s。！？!?，,、．.]/g,'')
 const selectedChoiceText=presentedQuestion.options?.find(option=>option.startsWith(`${selectedChoice}：`))?.slice(2).trim()
 const localAnswerMatches=presentedQuestion.options?cleaned(selectedChoiceText||input)===cleaned(presentedQuestion.answer)||cleaned(input)===cleaned(presentedQuestion.answer):cleaned(input)===cleaned(presentedQuestion.answer)
 const answerMatches=aiVerdict?aiVerdict==='correct'||aiVerdict==='mostly_correct':localAnswerMatches
 const missingPunctuation=answerMatches&&/[。．.]$/.test(presentedQuestion.answer)&&!/[。．.]$/.test(input.trim())
 const grade=()=>{const question=ex;submittedQuestion.current=question;setAiVerdict(null);setAnalysis(null);setGradeExplanation(localAnswerMatches?'句型结构正确，继续保持主动输出。':explainAnswerDifference(question.answer,selectedChoiceText||input));setGradeSource('rule');if(!localAnswerMatches){setMistakes(value=>value.some(item=>item.id===question.id)?value:[...value,question])}else if(practiceMode==='mistakes'){setMistakes(value=>value.filter(item=>item.id!==question.id))}if(userId)void (async()=>{try{const response=await fetch('/api/record-answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:question.id,lessonId:question.lessonId,answer:input,correct:localAnswerMatches,errorTags:localAnswerMatches?[]:['句型顺序'],mode:practiceMode==='lesson'?'lesson':'review'})});if(!response.ok)return;await response.json()}catch{console.warn('Unable to persist answer; using local fallback')}})();setGraded(true)}
 const analyzeAnswer=async()=>{setAnalysisLoading(true);try{const response=await fetch('/api/analyze-answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:presentedQuestion.prompt,answer:input,standardAnswer:presentedQuestion.answer,hint:presentedQuestion.hint})});setAnalysis(await response.json())}catch{setAnalysis({analysis:'AI 分析暂时不可用，请对照标准答案拆分词语和句型记忆。',source:'fallback'})}finally{setAnalysisLoading(false)}}
 const displayCorrect=aiVerdict?aiVerdict==='correct'||aiVerdict==='mostly_correct':answerMatches
 const startPractice=(_mode:'new'|'review'='new',lessonIndex=active)=>{submittedQuestion.current=null;setSelectedChoice('');setFullLessonMode(true);setFullLessonProgress(0);setSessionProgress(0);setPracticeMode('lesson');setActive(lessonIndex);setInput('');setAiVerdict(null);setGraded(false);setTab('practice')}
 const startLessonPractice=(lessonIndex=active)=>{submittedQuestion.current=null;setSelectedChoice('');setFullLessonMode(true);setFullLessonProgress(0);setSessionProgress(0);setLessonCorrect(value=>({...value,[lessonIndex]:0}));setActive(lessonIndex);setInput('');setAiVerdict(null);setGraded(false);setTab('practice')}
 const startMistakePractice=()=>{if(mistakes.length){submittedQuestion.current=null;setPracticeMode('mistakes');setFullLessonMode(false);setSessionProgress(0);setInput('');setAiVerdict(null);setGraded(false);setTab('practice')}}
 const startMixedPractice=()=>{const questions=createMixedReviewSet(completedLessons,20);if(questions.length){setMixedQuestions(questions);submittedQuestion.current=null;setPracticeMode('mixed');setFullLessonMode(false);setSessionProgress(0);setInput('');setAiVerdict(null);setGraded(false);setTab('practice')}}
 const nextQuestion=()=>{const complete=progress>=sessionLimit-1;const finalCorrect=(lessonCorrect[active]??0)+(answerMatches?1:0);if(practiceMode==='lesson'){setFullLessonProgress(value=>value+1);setLessonDone(value=>({...value,[active]:Math.min(questionsForLesson(active+1).length||20,(value[active]??0)+1)}));setLessonCorrect(value=>({...value,[active]:finalCorrect}));if(complete&&finalCorrect/sessionLimit>=0.9)setCompletedLessons(value=>value.includes(active)?value:[...value,active])}setSessionProgress(value=>value+1);submittedQuestion.current=null;setSelectedChoice('');setInput('');setGraded(false);if(complete)setTab('home')}
 const currentLesson=displayedLessons[nextLessonIndex]??displayedLessons[0]
 const overallProgress=Math.round(displayedLessons.reduce((sum,lesson)=>sum+lesson.progress,0)/displayedLessons.length)
 const learnerName=userEmail?userEmail.split('@')[0]:'学习者'
 const totalAnswered=Object.values(lessonDone).reduce((sum,count)=>sum+count,0)
 return <main className="shell">
   <header><div className="brand"><span className="brand-mark">文</span><div><strong>句型教练</strong><small>标准日本语 · 上册</small></div></div><div className="streak">第 {currentLesson.id} 课</div><button className="avatar" onClick={()=>setTab('me')}>{learnerName.slice(0,1).toUpperCase()}</button></header>
  {tab==='home'&&<><section className="hero"><div><p className="eyebrow">早上好，{learnerName}</p><h1>一课一课练习，<br/><em>把句型练成反射。</em></h1><p className="muted">完成本课 20 道题，正确率达到 90% 后解锁下一课。</p><button className="primary" onClick={()=>startLessonPractice(nextLessonIndex)}>开始第 {currentLesson.id} 课 <span>→</span></button></div><div className="orb" style={{background:`conic-gradient(var(--green) 0 ${currentLesson.progress}%,#dfe9e3 ${currentLesson.progress}%`}}><div className="orb-inner">本课<br/><b>{currentLesson.progress}%</b></div></div></section>
   {completedLessons.some(index=>(index+1)%5===0)&&<button className="secondary wide" onClick={startMixedPractice}>开始综合混练（已完成课程） <span>→</span></button>}
   <section className="stats"><div><b>{currentLesson.progress}%</b><span>本课进度</span></div><div><b>第 {currentLesson.id} 课</b><span>继续学习</span></div><div><b>{overallProgress}%</b><span>整体掌握</span></div></section>
   <section className="section-head"><div><p className="eyebrow">继续学习</p><h2>{currentLesson.progress>0?'接着上次学习':'从第一课开始'}</h2></div><button className="link" onClick={()=>setTab('lessons')}>查看全部 →</button></section>
<div className="lesson-card" onClick={()=>{setActive(nextLessonIndex);setTab('lesson')}}><div className="lesson-no">{String(currentLesson.id).padStart(2,'0')}</div><div className="lesson-info"><div className="tag">第 {currentLesson.id} 课</div><h3>{currentLesson.title}</h3><p>{currentLesson.grammar.map(g=>g.pattern).join(' · ')}</p><div className="progress"><i style={{width:`${currentLesson.progress}%`}}/></div><small>{currentLesson.progress?`已掌握 ${currentLesson.progress}%`:'尚未开始'}</small></div><span className="arrow">→</span></div>
  </>}
  {tab==='lessons'&&<><div className="page-title"><p className="eyebrow">课程地图</p><h1>标准日本语·上册</h1><p className="muted">24 课 · 从句型骨架开始，逐步建立语感</p></div><div className="lesson-grid">{lessons.map(l=><button key={l.id} className={'lesson-tile '+(l.locked?'locked':'')} onClick={()=>!l.locked&&(setActive(l.id-1),setTab('lesson'))}><span>{String(l.id).padStart(2,'0')}</span><div><b>第 {l.id} 课</b><small>{l.title}</small>{!l.locked&&<div className="mini-progress"><i style={{width:`${l.progress}%`}}/></div>}</div><em>{l.locked?'🔒':l.progress+'%'}</em></button>)}</div></>}
  {tab==='lesson'&&<><button className="back" onClick={()=>setTab('home')}>← 返回</button><div className="page-title"><div className="tag">第 {selectedLesson.id} 课 · 核心句型</div><h1>{selectedLesson.title}</h1><p className="muted">{selectedLesson.goal}</p></div><div className="grammar-list">{selectedLesson.grammar.map((g,i)=><div className="grammar" key={i}><span>0{i+1}</span><div><b>{g.pattern}</b><p>{g.meaning}</p><small>接续：{g.connection}</small><small>说明：{g.explanation}</small><small>例句：{g.example}</small>{g.responses?.map(response=><small className="grammar-extra" key={response}>应答：{response}</small>)}{g.pitfalls?.map(pitfall=><small className="grammar-extra" key={pitfall}>易错：{pitfall}</small>)}</div><button onClick={()=>speechSynthesis?.speak(new SpeechSynthesisUtterance(g.example))}>🔊</button></div>)}</div><button className="primary wide" onClick={()=>startLessonPractice(active)}>开始整课练习（{questionsForLesson(selectedLesson.id).length} 题） <span>→</span></button>{active<displayedLessons.length-1&&<div className="next-preview"><b>下一课预告：第 {selectedLesson.id+1} 课</b><p>{displayedLessons[active+1].goal}</p><small>完成本课全部题目且正确率达到 90% 后解锁</small></div>}</>}
  {tab==='practice'&&<><div className="practice-top"><button className="back" onClick={()=>setTab('home')}>× 退出</button><span>{practiceMode==='mistakes'?'错题练习':`第 ${selectedLesson.id} 课 · 练习`}</span><b>{Math.min(progress+1,sessionLimit)} / {sessionLimit}</b></div><div className="quiz"><div className="quiz-meta"><span className="tag">{presentedQuestion.type}</span><span>句型骨架</span></div><h2>把下面的中文说成日语</h2><div className="prompt">{presentedQuestion.prompt}</div>{presentedQuestion.options?<div className="choice-list">{presentedQuestion.options.map(option=><button key={option} className={selectedChoice===option.slice(0,1)?'choice selected':''} onClick={()=>{if(!graded){const value=option.slice(0,1);setSelectedChoice(value);setInput(value)}}} disabled={graded}>{option}</button>)}</div>:<textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="在这里输入你的答案…" disabled={graded}/>} {graded&&<div className={'feedback '+(answerMatches?'ok':'warn')}><b>{answerMatches?'✓ 很好，句型正确':'△ 句型或词语还需要调整'}</b><p>参考答案：{presentedQuestion.answer}</p>{gradeExplanation&&<small>{gradeSource==='ai'?'AI 批改：':'规则批改：'}{gradeExplanation}</small>}{missingPunctuation&&<small>答案判定正确；下次书写时不要忘记写标点符号。</small>}{!answerMatches&&<><small>提示：{presentedQuestion.hint}<br/>书写时不要忘记写标点符号，标点不影响判分。</small></>}{!analysis&&<button className="analysis-button" onClick={analyzeAnswer} disabled={analysisLoading}>{analysisLoading?'分析中…':'AI 分析记忆方法'}</button>}{analysis&&<div className="analysis"><p>{analysis.analysis}</p>{analysis.words?.map(word=><div key={word.word}><b>{word.word}（{word.kana}）</b><span>{word.meaning} · {word.memory}</span></div>)}{analysis.pitfalls?.map(pitfall=><small key={pitfall}>易错点：{pitfall}</small>)}</div>}</div>}<button className="primary wide" onClick={()=>graded?nextQuestion():grade()} disabled={!graded&&presentedQuestion.type==='选择'&&!selectedChoice}>{graded?(progress>=sessionLimit-1?'完成训练':'下一题'):'提交答案'} <span>→</span></button></div></>}
  {tab==='mistakes'&&<><div className="page-title"><p className="eyebrow">复习重点</p><h1>错题本</h1><p className="muted">把容易忘的地方，再练一次。</p></div>{mistakes.length>0&&<button className="primary wide" onClick={startMistakePractice}>开始错题练习（{mistakes.length} 题）</button>}{mistakes.map(item=><div className="mistake-card" key={item.id}><div className="mistake-icon">文</div><div><b>{item.prompt}</b><p>第 {item.lessonId} 课 · {item.type}</p><small>参考答案：{item.answer}</small></div><span>→</span></div>)}{mistakes.length===0&&<div className="empty-note">目前没有错题<br/>完成练习后，错题会自动收录。</div>}</>}
  {tab==='me'&&<><div className="page-title"><p className="eyebrow">个人中心</p><h1>我的</h1><p className="muted">学习记录会在登录后同步到云端。</p></div><div className="profile-card"><div className="profile-avatar">{userEmail?userEmail.slice(0,1).toUpperCase():'N'}</div><div><h2>{userEmail||'N 学习者'}</h2><p>{userEmail?'已登录':'尚未登录'}</p></div><button className="outline" onClick={()=>location.href='/login'}>{userEmail?'切换账号':'登录 / 注册'}</button></div>{userEmail&&<div className={'sync-note '+syncState}>{syncState==='syncing'?'正在同步学习记录…':syncState==='failed'?'同步失败，请检查网络后重试。':syncState==='synced'?'学习记录已同步到云端。':'仅保存在当前设备。'}{syncState==='failed'&&<button onClick={()=>setSyncRetry(value=>value+1)}>重试</button>}</div>}<div className="profile-stats"><div><b>第 {currentLesson.id} 课</b><span>当前课程</span></div><div><b>{overallProgress}%</b><span>学习进度</span></div><div><b>{totalAnswered}</b><span>累计练习</span></div></div><div className="info-list"><div><span>同步状态</span><b>{userEmail?(syncState==='failed'?'需要重试':syncState==='syncing'?'同步中':syncState==='synced'?'已同步':'仅本机'):'登录后同步'}</b></div><div><span>已完成课程</span><b>{completedLessons.length} / 24</b></div><div><span>累计练习</span><b>{totalAnswered} 题</b></div></div></>}
  <nav><button className={tab==='home'?'selected':''} onClick={()=>setTab('home')}>⌂<small>首页</small></button><button className={tab==='lessons'||tab==='lesson'?'selected':''} onClick={()=>setTab('lessons')}>▤<small>课程</small></button><button className={tab==='mistakes'?'selected':''} onClick={()=>setTab('mistakes')}>☆<small>错题本</small></button><button className={tab==='me'?'selected':''} onClick={()=>setTab('me')}>◎<small>我的</small></button></nav>
 </main>
}
